spring:
  application:
    name: stockservice
server:
  port: 8503
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8501/eureka/
  instance:
    hostname: localhost

